name: Build
on: [ push, pull_request ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Android build cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.android/build-cache
          key: ${{ runner.os }}-android
          restore-keys: ${{ runner.os }}-android

      - name: Set up JDK 21
        uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5.7.0
        with:
          distribution: 'corretto'
          java-version: 21
          cache: 'gradle'

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Build
        env:
          NEXTCLOUD_URL: ${{ vars.NEXTCLOUD_URL }}
          NEXTCLOUD_USER: ${{ secrets.NEXTCLOUD_USER }}
          NEXTCLOUD_PASS: ${{ secrets.NEXTCLOUD_PASS }}
        run: ./gradlew compileDebugAndroidTestSources check assemble ktlintCheck

      - name: Upload APKs
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: seedvault-${{ github.sha }}-apks
          path: |
            app/build/outputs/apk/debug/app-debug.apk
            contactsbackup/build/outputs/apk/debug/contactsbackup-debug.apk
            storage/demo/build/outputs/apk/debug/demo-debug.apk

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@d9f48fc87bc235f7e214acf696ca5abc0a986f16
        if: success() || failure()
        with:
          report_paths: '**/build/test-results/**/TEST-*.xml'

